# Generated by Django 4.1.3 on 2023-08-15 09:33

import attendance.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to=attendance.models.student_directory_path,
            ),
            preserve_default=False,
        ),
    ]
