# Generated by Django 4.1.3 on 2023-08-15 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_customuser_alter_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="year",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
