# Generated by Django 4.1.3 on 2023-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_customuser_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
